### ISSUE TITLE
info k senzitivite lockinu

### ISSUE THREAD

**Issue by sm0XY** [TIS2022-FMFI/spektra#22]

**Comment by Nesciuse** [comment]
Toto je z nahravky co hovoril ohladom tej senzitivity `"Este to ma jeden  problem ale to ani neni problem tej komunikacie ale je taky problem ze niekedy sa ten signal strati ze je strasne slaby z roznych dovodov a vtedy sa ten lockin prepina az na najcitlivejsi rozshah co sa moze odpalit v zasade ked do neho zasvieti. Tak ja som to tu niekde limitoval ze pod nejaky gain to nepojde. Cize ja si to akoze pamatam ze to je ten limit a je to tu v programe a ked to potrebujem zmenit ked je slaby signal nejaky co meriam tak si to zmenim tu na meriam slaby signal. Takze to len taka poznamka cize ked to budete uz programovat cez nejake rozhranie inteligentne nie taketo tak mozno by tam bolo namieste dat take ze spodny limit."`

**Comment by Nesciuse** [comment]
A ak som spravne pochopil je tam podmienka 
```if u1 <= .1*gain[g] and g>=12:          #ak je hodnota mensia nez 30% rozsahu
            g=g-1                   #zvacsi zisk
            ser.write('G'+' '+str(g)+'\r')
            print ("Zosilnenie sa zvyslo na "+ str(g)+" "+str(gain[g])+"\n")
            # time.sleep(20*time1[t1]) #cakaj 3 casove konstanty```

cize minimalne g moze byt 11 co je 20 mikrovoltov senzitivita
