### ISSUE TITLE
Celková revízia katalógu požiadaviek

### ISSUE THREAD

**Issue by sm0XY** [TIS2022-FMFI/spektra#28]
robia všetci
po rev2

**Comment by pavelpetrovic** [comment]
prosim upravit posledne drobnosti,
zistit, ci je to naozaj tak, ze uhol mriezky a uhol krokoveho motora nie su 1:1
a podla toho aktualizovat formulacie

[SpecifikaciaSpektra_s_novymi_komentarmi.docx](https://github.com/TIS2022-FMFI/spektra/files/9969621/SpecifikaciaSpektra_s_novymi_komentarmi.docx)

**Comment by Bonnie404** [comment]
[SpecifikaciaSpektra.pdf](https://github.com/TIS2022-FMFI/spektra/files/10019585/SpecifikaciaSpektra.pdf)
