### ISSUE TITLE
Vytvorenie katalógu požiadaviek

### ISSUE THREAD

**Issue by sm0XY** [TIS2022-FMFI/spektra#9]

**Comment by pavelpetrovic** [comment]
par drobnosti:
* cislovanie kapitol v obsahu?
* prosim rozpisat poskytnute dokumenty (ich nazvy)
* prosim vysvetlit vetu "Podľa potreby môžeme zväčšovať alebo skryť niektoré konfiguračné okná v užívateľskom rozhraní."
* 1.2. prva veta je necitatelna
* ja som 1.2. pochopil tak, ze aplikacia bude vediet naraz komunikovat s viacerymi, tak prosim upresnit (komunikáciu s viacerými prístrojmi)
* 2.4. nerozumiem celkom co s tymi nastavenymi udajmi - niekde sa zaznamenaju v pocitaci?  (spomente)
* potrebujeme puntiky pri poziadvkach?
* Lock-2  prosim upresnit ake parametre a ake moznosti nastaveni
* bude mozne nastavit aj komunikacne parametre so zariadenim (baud rate, stop bits, data bits...)?
* Lock-6 - automaticky - tu mi chybaju informacie, treba to upresnit
* vsetky poziadavky maju byt cele vety. Aplikacia umozni.... Pouzivatel moze....  nie heslovity zoznam
* Lock-7 - co to znamena?
* Lock-8 - mame aj ich typy?
* KrokMot-1 - zrejme tiez cez seriovy port a nastavenia komunikacie budu niekde ulozene
* KrokMot-2 - chybaju informacie a o kolko sa motor posuva?
* KrokMot-3 - co z toho vyplyva?
* KrokMot-4 - ako? iba ano/nie alebo aj urcit nejake zrychlenie?
* Data-1 - odkial idu data ake data kolko?
* podobne prosim upravit aj ostatne body

**Comment by lk0103** [comment]
Lucia - 
cislovanie kapitol v obsahu?
prosim rozpisat poskytnute dokumenty (ich nazvy)
prosim vysvetlit vetu "Podľa potreby môžeme zväčšovať alebo skryť niektoré konfiguračné okná v užívateľskom rozhraní."
1.2. prva veta je necitatelna
ja som 1.2. pochopil tak, ze aplikacia bude vediet naraz komunikovat s viacerymi, tak prosim upresnit (komunikáciu s viacerými prístrojmi)

**Comment by Bonnie404** [comment]
2.4. nerozumiem celkom co s tymi nastavenymi udajmi - niekde sa zaznamenaju v pocitaci? (spomente) - spomenute

**Comment by Bonnie404** [comment]
Lock-2 prosim upresnit ake parametre a ake moznosti nastaveni

**Comment by Bonnie404** [comment]
bude mozne nastavit aj komunikacne parametre so zariadenim (baud rate, stop bits, data bits...)? : dolpnene, nebude to mozne menit pouzivatelom

**Comment by Bonnie404** [comment]
Lock-6 - automaticky - tu mi chybaju informacie, treba to upresnit. :  odstranene slovo automaticky. Dolpneny dovod.

**Comment by Bonnie404** [comment]
vsetky poziadavky maju byt cele vety. Aplikacia umozni.... Pouzivatel moze.... nie heslovity zoznam . Prefrázovaná časť s lockinom.

**Comment by Bonnie404** [comment]
Lock-8 - mame aj ich typy? Nemáme. Po rozhovore so zadávateľom sme zistli, že jednotlivé typy lockinov si budú vyžadovať rôzne možnosti v nastaveniach priamo v aplikácii. Aplikácia bude predpripravená na to, aby sa dali tieto ďalšie menu doprogramovať v budúcnosti po vzore milivoltmetra SR510. Doplnená požiadavka v lock-10.

**Comment by Bonnie404** [comment]
Lock-7 - co to znamena? dolpnene

**Comment by Bonnie404** [comment]
KrokMot-1 - zrejme tiez cez seriovy port a nastavenia komunikacie budu niekde ulozene. Doplnene

**Comment by Bonnie404** [comment]
KrokMot-2 - chybaju informacie a o kolko sa motor posuva? Doplnene

**Comment by Bonnie404** [comment]
KrokMot-3 - co z toho vyplyva? Po nastavení uhlu pouzivatelom sa dá vypocitat krok motora. Potom pouzivatel moze nastavit lubovolnu poziciu a motor sa tam posunie tym sposobom, ze sa bude vediet vratit do bodu 0 a odtial potom vie ist kamkolvek dalej (vieme mu poslat kolko krokov musi urobit, pretoze pozname dlzku kroku). Preformulovane.

**Comment by Bonnie404** [comment]
KrokMot-4 - ako? iba ano/nie alebo aj urcit nejake zrychlenie? Doplnene.

**Comment by Bonnie404** [comment]
Data-1 - odkial idu data ake data kolko? Doplnene

**Comment by Bonnie404** [comment]
Dokoncena uprava sekcie Špecifické požiadavky

**Comment by Bonnie404** [comment]
Dokoncena uprava sekcie Kvalitatívne požiadavky

**Comment by Bonnie404** [comment]
Dokoncena uprava sekcie  Požiadavky na rozhranie

**Comment by pavelpetrovic** [comment]
do dokumentu som pridal par otazok a komentarov.
prosim dotiahnite to do jednoznacnej verzie, nad ktorym uz nebudeme musiet badat, ked ho budeme pouzivat pri navrhu a testovani a potom dokument uz pouzite na vyjednavanie o finalnej verzii dokumentu so zadavatelom. vyhradzujem si este moznost nieco "ofrflat", ale verim, ze to uz nebude treba, lebo to bude vyborne. dakujem.
